// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHAviModL53y9N8e62yL2VJnfElbvbJXs',
    appId: '1:1085363878255:web:471d1caa5797b05ce9909a',
    messagingSenderId: '1085363878255',
    projectId: 'cricket-app-211a7',
    authDomain: 'cricket-app-211a7.firebaseapp.com',
    storageBucket: 'cricket-app-211a7.firebasestorage.app',
    measurementId: 'G-8NHE8PHPVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvqu-bmQgpbp1Mtpk2a24Cj3yXjahmQMo',
    appId: '1:1085363878255:android:de61d604d35a27d3e9909a',
    messagingSenderId: '1085363878255',
    projectId: 'cricket-app-211a7',
    storageBucket: 'cricket-app-211a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpiKuZ9bEXV4MItWO-tx9TBhcCxmBbzkU',
    appId: '1:1085363878255:ios:ef64ff2685eb8522e9909a',
    messagingSenderId: '1085363878255',
    projectId: 'cricket-app-211a7',
    storageBucket: 'cricket-app-211a7.firebasestorage.app',
    iosClientId: '1085363878255-0rfumaajc7fub0chm448at4b633oln8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.cricketScoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpiKuZ9bEXV4MItWO-tx9TBhcCxmBbzkU',
    appId: '1:1085363878255:ios:ef64ff2685eb8522e9909a',
    messagingSenderId: '1085363878255',
    projectId: 'cricket-app-211a7',
    storageBucket: 'cricket-app-211a7.firebasestorage.app',
    iosClientId: '1085363878255-0rfumaajc7fub0chm448at4b633oln8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.cricketScoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHAviModL53y9N8e62yL2VJnfElbvbJXs',
    appId: '1:1085363878255:web:269b3f388721e8a8e9909a',
    messagingSenderId: '1085363878255',
    projectId: 'cricket-app-211a7',
    authDomain: 'cricket-app-211a7.firebaseapp.com',
    storageBucket: 'cricket-app-211a7.firebasestorage.app',
    measurementId: 'G-PC2SGJ1M00',
  );
}
